src/SprintPlanner.Web/Models/ErrorViewModel.cs
namespace SprintPlanner.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/SprintPlanner.Web/Models/SprintViewModel.cs
namespace SprintPlanner.Web.Models;

public class SprintViewModel
{
    public List<DeveloperDto> Developers { get; set; } = null!;
    public List<SprintTaskDto> Tasks { get; set; } = null!;
}

src/SprintPlanner.Web/Controllers/HomeController.cs
using System.Diagnostics;

namespace SprintPlanner.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/SprintPlanner.Web/Controllers/SprintController.cs
namespace SprintPlanner.Web.Controllers;

public class SprintController : Controller
{
    private readonly IMediator _mediator;

    public SprintController(IMediator mediator)
    {
        Guard.Against.Null(mediator, nameof(mediator));

        _mediator = mediator;
    }

    public async Task<IActionResult> Index(CancellationToken cancellationToken)
    {
        var viewModel = new SprintViewModel
        {
            Developers = await _mediator.Send(new GetAllDevelopersQuery(), cancellationToken),
            Tasks = await _mediator.Send(new GetAllSprintTasksQuery(), cancellationToken)
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Schedule(PlanningAlgorithmType algorithmType, CancellationToken cancellationToken)
    {
        await _mediator
            .Send(new AssignTasksToDevelopersCommand(algorithmType), cancellationToken);

        var model = await _mediator
            .Send(new GetAllDevelopersWithTasksQuery(), cancellationToken);

        return View(model);
    }
}

src/SprintPlanner.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/SprintPlanner.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SprintPlanner.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SprintPlanner.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SprintPlanner.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Sprint" asp-action="Index">Sprint Planner</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - SprintPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/SprintPlanner.Web/Views/Sprint/Index.cshtml
@model SprintViewModel
@{
    ViewData["Title"] = "Sprint";
    var planningAlgorithmType = new SelectList(Enum.GetValues<PlanningAlgorithmType>());
}

<div class="row">
    <div class="col">
        <h2>Developers</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Duration</th>
                <th scope="col">Difficulty</th>
            </tr>
            </thead>
            <tbody>

            @foreach (var developer in Model.Developers)
            {
                <tr>
                    <th scope="row">@developer.Id</th>
                    <td>@developer.Name</td>
                    <td>@developer.Duration</td>
                    <td>@developer.Difficulty.ToString()</td>
                </tr>
            }
            </tbody>
        </table>
    </div>

    <div class="col">
        <h2>Tasks</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Duration</th>
                <th scope="col">Difficulty</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var task in Model.Tasks)
            {
                <tr>
                    <th scope="row">@task.Id</th>
                    <td>@task.Name</td>
                    <td>@task.Duration</td>
                    <td>@task.Difficulty.ToString()</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <form asp-action="Schedule" method="post" class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
            <label>Planning Algorithm Type</label>
            <select class="form-select" name="algorithmType" asp-items="planningAlgorithmType">
            </select>
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Schedule</button>
        </div>
    </form>
</div>

src/SprintPlanner.Web/Views/Sprint/Schedule.cshtml
@model List<DeveloperWithTasksDto>
@{
    ViewData["Title"] = "Sprint Schedule";
}
<h4 class="text-center py-2">Weekly Task Schedule</h4>
<div class="row justify-content-center">
    @foreach (var developer in Model)
    {
        <div class="col-lg-4 mb-4">
            <div class="border p-3">
                <h5 class="text-center">@developer.Name</h5>
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Difficulty</th>
                        <th>Duration</th>
                        <th>Expected Duration</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    @{
                        double totalHour = 0;
                    }
                    @foreach (var task in developer.Tasks)
                    {
                        <tr>
                            <td>@task.Id</td>
                            <td>@task.Name</td>
                            <td>@task.Difficulty</td>
                            <td>@task.Duration</td>
                            <td>@TimeSpan.FromHours(task.ExpectedDuration).ToString("hh':'mm")</td>
                            <td>
                                @{ totalHour += task.ExpectedDuration; }
                                @TimeSpan.FromSeconds(totalHour * 3600).ToString("c")
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
                <div class="text-end mt-3">
                    Total: @($"{Math.Round(totalHour) / 45:F2} week")
                </div>
            </div>
        </div>
    }
</div>